version: '3'
services:
  dbservice:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bootapp

  appservice:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/invoicedb
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8080:8086"
    networks:
      - bootapp

networks:
  bootapp:
    driver: bridge
